[options]

admin_passwd = admin

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/custom,/mnt/extra-addons/community

logfile = /var/log/odoo/odoo.log

proxy_mode = False

list_db = True

data_dir = /var/lib/odoo